#!/usr/bin/python3

"""
Generate a nonrepeating pattern of bytes with prefix of n length.
"""

import sys
import argparse

parser = argparse.ArgumentParser(description="Generate a fuzzer string to target EIP.")
parser.add_argument("length", type=int, help="length of the prefix")
args = parser.parse_args()

prefix = 'A' * args.length

chars = ''
for a in range(0x41, 0x5A):
    for i in range(0x30, 0x3A):
        for j in range(0x30, 0x3A):
            chars += chr(a) + chr(a) + chr(i) + chr(j)

padding = 'F' * 3000

attack = prefix + chars + padding

print(attack)
